version: '3.8'
#apiVersion: networking.istio.io/v1alpha3
#kind: VirtualService
#metadata:
#    name: review-service
#spec:
#    hosts:
#     - review-service
#    http:
#     - route:
#         - destination:
#                host: review-service
#                subset: v2
#           weight: 10
#         - destination:
#               host: order-service
#               subset: v2
#           weight: 10

services:
  book-service:
    build: ./book_service
    ports:
      - "5001:5001"
    volumes:
      - ./book_service:/app
      - book_data:/app/data
    networks:
      - booknet

  review-service:
    build: ./review_service
    ports:
      - "5002:5002"
    volumes:
      - ./review_service:/app
      - review_data:/app/data
    environment:
      - BOOK_SERVICE_URL=http://book-service:5001/api/books
    networks:
      - booknet
    depends_on:
      - book-service

  web-interface:
    build: ./web_interface
    ports:
      - "3000:3000"
    volumes:
      - ./web_interface:/app
    networks:
      - booknet
    depends_on:
      - book-service
      - review-service

  api_gateway:
    build: ./api_gateway
    ports:
     - "8000:8000"
    volumes:
     - ./api_gateway:/app
    networks:
     - booknet
    depends_on:
     - web-interface
     - review-service
     - book-service


networks:
  booknet:
    driver: bridge


volumes:
  book_data:
  review_data:
